# Generated by Django 5.0.7 on 2024-09-01 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HabitConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "verbose_name": "Связь привычек",
                "verbose_name_plural": "Связи привычек",
            },
        ),
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Место, в котором необходимо выполнять привычку. Пример: улица, дом",
                        max_length=150,
                        verbose_name="Место",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        blank=True,
                        help_text="Время, когда необходимо выполнять привычку (формат чч:мм), не обязательное поле",
                        null=True,
                        verbose_name="Время",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Действие, которое представляет собой привычка. Пример: Бегать, Делать зарядку, Есть вкусняшки",
                        max_length=200,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False,
                        help_text="Привычка, которую можно привязать к выполнению полезной привычки. True (если это приятная привычка), False (если это полезная привычка)",
                        verbose_name="Признак приятной привычки",
                    ),
                ),
                (
                    "periodicity",
                    models.SmallIntegerField(
                        help_text="Пример: 1 (ежедневно), 7 (раз в неделю).",
                        verbose_name="Периодичность выполнения привычки в днях.",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Описание вознаграждения за выполнение полезной привычки.Пример: Сало, Сериал",
                        max_length=200,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "duration",
                    models.SmallIntegerField(
                        help_text="Предполагаемое время на выполнение привычки в секундах. Пример: 60 - время выполнения 1 минута)",
                        verbose_name="Время на выполнение",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Указывает на публичность привычки (может ли она быть видна другим пользователям). True (публичная), False (частная)",
                        verbose_name="Признак публичности",
                    ),
                ),
                (
                    "linked_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Пример: 'Прогулка' может быть связана с 'Чтением книги' как вознаграждение.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                        verbose_name="Ссылка на другую привычку, которая связана с текущей (только для полезных привычек)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
