# Generated by Django 5.0.7 on 2024-09-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_habit_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.SmallIntegerField(
                help_text="Пример: 1 (один раз в неделю), 7 (ежедневно).",
                verbose_name="Периодичность выполнения привычки в днях.",
            ),
        ),
    ]
